language: python

python: 3.6

sudo: false

before_install:
 - pip install -r test-requirements.txt
 - flake8 -v .
 - rst-lint README.rst

script:
 - python setup.py sdist install || exit 1
 - python -c 'import idr'
 - IDR_HOST=idr.openmicroscopy.org IDR_USER=public IDR_PASSWORD=public pytest

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  on:
    tags: true
