# conda env create -f environment.yml -n idr-omero
channels:
  - ome
  - defaults
dependencies:
  # TODO: Replace omero-py withidr-py when it's added
  - omero-py>=5.6dev4
  - ipython
  - ipywidgets
  - matplotlib
  - pandas
  - requests
  - seaborn
  - pip:
    - idr-py
