# conda env create -f environment.yml -n idr-omero54
channels:
  - bioconda
  - defaults
dependencies:
  - python-omero>=5.4,<5.5
  - zeroc-ice=3.6.3
  - ipython
  - ipywidgets
  - matplotlib
  - pandas
  - requests
  - seaborn
  - pip:
    - idr-py
